manager = "pacman"

[apps]
general = [
  "firefox-nightly",
  "spotify",
  "steam",
  "discord",
  "mpv",
  "thunderbird",
  "ani-cli",
  "lutris",
  "evince",
  "alacritty",
  "zoxide",
]

required = [
  "linux-firmware",
  "wget",
  "curl",
  "yay",
  "tmux",
  "base",
  "xf86-video-intel",
]

[apps.window_manager]
hyprland = [ "hyprland-git", "hyprshot", "hyprpaper" ]
accessories = [ "waybar" ]
backup = [ "gnome" ]
other = [ "gdm", "pulseaudio", "pavucontrol" ]


[apps.programming]
lsp = ["rust-analyzer"]
editor = ["helix"]
compilers = ["gcc", "g++", "rustup", "cargo", "rustc", "python3", "npm", "zig"]
debuggers = ["gdb"]
